version: '3'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9099:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: my-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 157.66.218.191:9092
      DYNAMIC_CONFIG_ENABLED: true
