package com.gin.wegd.auth_service.comon;

public enum OtpPurpose {
    DELETE_ACCOUNT,
    VERIFY_PHONE_NUMBER,
    CHANGE_PHONE_NUMBER,
    FORGET_PASSWORD,
    CHANGE_PASSWORD,
    TWO_FACTOR_AUTHENTICATION_ENABLE,
    TWO_FACTOR_AUTHENTICATION_DISABLE,
    DELETE_KYC, TWO_FACTOR_AUTHENTICATION
}
